### ISSUE TITLE
Possible Bug in QueueManager PArams Validation

### ISSUE THREAD

**Issue by wokket** [AuDigitalHealth/mhr-store-and-forward#1]
The guard clause in QueueManager.GetDocumentQueueList seems to be inverted:

https://github.com/AuDigitalHealth/mhr-store-and-forward/blob/master/src/StoreAndForward.Core/Queue/QueueManager.cs#L167-L170

**Comment by adha-admin** [comment]
Thanks for raising the issue. We have addressed the problem - See comments.
